[mypy]
python_version = 3.13
exclude = (^|/)sib_tools/email/experimental/.*\.py$

[mypy-googleapiclient]
ignore_missing_imports = True

[mypy-googleapiclient.*]
ignore_missing_imports = True

[mypy-beaupy]
ignore_missing_imports = True

[mypy-dkim]
ignore_missing_imports = True
